[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']
viaIR = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
op_sepolia = "https://sepolia.optimism.io"
rise_sepolia = "https://testnet.riselabs.xyz"
arb_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base_sepolia= "https://sepolia.base.org"
cachain_sepolia = "http://44.213.128.45:8547/"
educhain = "https://rpc.open-campus-codex.gelato.digital"
pharos_devnet= "https://devnet.dplabs-internal.com"
avalanche_fuji="https://api.avax-test.network/ext/bc/C/rpc"
base_mainnet="https://virtual.base.rpc.tenderly.co/71ea1327-e33a-421d-8589-c203b22456d4"
eth_mainnet="https://eth-mainnet.g.alchemy.com/v2/Ea4M-V84UObD22z2nNlwDD9qP8eqZuSI"
etherlink_testnet="https://node.ghostnet.etherlink.com"

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
